// Mocks generated by Mockito 5.4.6 from annotations
// in tamyez_app/test/modules/auth/ui/screens/forget_password/view_model/forget_password_view_model.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tamyez_app/core/execution/operation_result.dart' as _i4;
import 'package:tamyez_app/core/utils/counter/count_down_utility.dart' as _i11;
import 'package:tamyez_app/modules/auth/domain/entities/reset_password_params.dart'
    as _i10;
import 'package:tamyez_app/modules/auth/domain/entities/user_email_params.dart'
    as _i5;
import 'package:tamyez_app/modules/auth/domain/entities/verify_code_params.dart'
    as _i8;
import 'package:tamyez_app/modules/auth/domain/use_case/forget_password_use_case.dart'
    as _i2;
import 'package:tamyez_app/modules/auth/domain/use_case/reset_password_use_case.dart'
    as _i9;
import 'package:tamyez_app/modules/auth/domain/use_case/verify_code_use_case.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUseCase extends _i1.Mock
    implements _i2.ForgetPasswordUseCase {
  @override
  _i3.Future<_i4.OperationResult<bool>> call({
    required _i5.UserEmailParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i3.Future<_i4.OperationResult<bool>>.value(
              _i6.dummyValue<_i4.OperationResult<bool>>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<bool>>.value(
                  _i6.dummyValue<_i4.OperationResult<bool>>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<bool>>);
}

/// A class which mocks [VerifyCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyCodeUseCase extends _i1.Mock implements _i7.VerifyCodeUseCase {
  @override
  _i3.Future<_i4.OperationResult<bool>> call({
    required _i8.VerifyCodeParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i3.Future<_i4.OperationResult<bool>>.value(
              _i6.dummyValue<_i4.OperationResult<bool>>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<bool>>.value(
                  _i6.dummyValue<_i4.OperationResult<bool>>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<bool>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i9.ResetPasswordUseCase {
  @override
  _i3.Future<_i4.OperationResult<bool>> call({
    required _i10.ResetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#params: params}),
            returnValue: _i3.Future<_i4.OperationResult<bool>>.value(
              _i6.dummyValue<_i4.OperationResult<bool>>(
                this,
                Invocation.method(#call, [], {#params: params}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<bool>>.value(
                  _i6.dummyValue<_i4.OperationResult<bool>>(
                    this,
                    Invocation.method(#call, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<bool>>);
}

/// A class which mocks [CountDownUtility].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountDownUtility extends _i1.Mock implements _i11.CountDownUtility {
  @override
  bool get isCountdownRunning =>
      (super.noSuchMethod(
            Invocation.getter(#isCountdownRunning),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void startCountdown({
    required int? seconds,
    required void Function(int)? onTick,
    required void Function()? onFinished,
  }) => super.noSuchMethod(
    Invocation.method(#startCountdown, [], {
      #seconds: seconds,
      #onTick: onTick,
      #onFinished: onFinished,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void cancelCountdown() => super.noSuchMethod(
    Invocation.method(#cancelCountdown, []),
    returnValueForMissingStub: null,
  );
}
