arb-dir: lib/core/layers/localization/l10n/arb_files
template-arb-file: app_en.arb
output-dir: lib/core/layers/localization/l10n/generated
output-localization-file: app_localizations.dart

# command: flutter gen-l10n