// Mocks generated by Mockito 5.4.6 from annotations
// in tamyez_app/test/modules/onboarding/onboarding_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tamyez_app/core/presentation/result/ui_effect.dart' as _i5;
import 'package:tamyez_app/modules/auth/ui/screens/login/view_model/login_intent.dart'
    as _i6;
import 'package:tamyez_app/modules/auth/ui/screens/login/view_model/login_state.dart'
    as _i2;
import 'package:tamyez_app/modules/auth/ui/screens/login/view_model/login_view_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginState_0 extends _i1.SmartFake implements _i2.LoginState {
  _FakeLoginState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginViewModel extends _i1.Mock implements _i3.LoginViewModel {
  @override
  _i4.Stream<_i5.UiEffect> get effectStream =>
      (super.noSuchMethod(
            Invocation.getter(#effectStream),
            returnValue: _i4.Stream<_i5.UiEffect>.empty(),
            returnValueForMissingStub: _i4.Stream<_i5.UiEffect>.empty(),
          )
          as _i4.Stream<_i5.UiEffect>);

  @override
  _i2.LoginState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeLoginState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeLoginState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.LoginState);

  @override
  _i4.Stream<_i2.LoginState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.LoginState>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.LoginState>.empty(),
          )
          as _i4.Stream<_i2.LoginState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> doIntent(_i6.LoginIntent? intent) =>
      (super.noSuchMethod(
            Invocation.method(#doIntent, [intent]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emitEffect(_i5.UiEffect? effect) => super.noSuchMethod(
    Invocation.method(#emitEffect, [effect]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emit(_i2.LoginState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i2.LoginState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
