// Mocks generated by Mockito 5.4.6 from annotations
// in tamyez_app/test/modules/auth/data/repositories/auth_repo_imp.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:firebase_core/firebase_core.dart' as _i6;
import 'package:firebase_messaging/firebase_messaging.dart' as _i20;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:tamyez_app/core/network/models/login_session_dto.dart' as _i5;
import 'package:tamyez_app/core/network/models/simple_api_response.dart' as _i4;
import 'package:tamyez_app/core/utils/device_id/device_id_service.dart' as _i19;
import 'package:tamyez_app/modules/auth/data/data_sources/local/auth_local_data_source.dart'
    as _i18;
import 'package:tamyez_app/modules/auth/data/data_sources/remote/auth_remote_data_source.dart'
    as _i8;
import 'package:tamyez_app/modules/auth/data/data_sources/remote/social_auth_service.dart'
    as _i16;
import 'package:tamyez_app/modules/auth/data/models/gmail_login_request.dart'
    as _i11;
import 'package:tamyez_app/modules/auth/data/models/login_request.dart' as _i13;
import 'package:tamyez_app/modules/auth/data/models/login_response.dart' as _i3;
import 'package:tamyez_app/modules/auth/data/models/reset_password_request.dart'
    as _i15;
import 'package:tamyez_app/modules/auth/data/models/sign_up_request.dart'
    as _i10;
import 'package:tamyez_app/modules/auth/data/models/sign_up_response.dart'
    as _i2;
import 'package:tamyez_app/modules/auth/data/models/user_email_request.dart'
    as _i12;
import 'package:tamyez_app/modules/auth/data/models/verify_code_request.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignUpResponse_0 extends _i1.SmartFake
    implements _i2.SignUpResponse {
  _FakeSignUpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleApiResponse_2 extends _i1.SmartFake
    implements _i4.SimpleApiResponse {
  _FakeSimpleApiResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginSessionDto_3 extends _i1.SmartFake
    implements _i5.LoginSessionDto {
  _FakeLoginSessionDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_4 extends _i1.SmartFake implements _i6.FirebaseApp {
  _FakeFirebaseApp_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_5 extends _i1.SmartFake
    implements _i7.NotificationSettings {
  _FakeNotificationSettings_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i8.AuthRemoteDataSource {
  @override
  _i9.Future<_i2.SignUpResponse> signUp({
    required _i10.SignUpRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {#request: request}),
            returnValue: _i9.Future<_i2.SignUpResponse>.value(
              _FakeSignUpResponse_0(
                this,
                Invocation.method(#signUp, [], {#request: request}),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i2.SignUpResponse>.value(
              _FakeSignUpResponse_0(
                this,
                Invocation.method(#signUp, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i2.SignUpResponse>);

  @override
  _i9.Future<_i3.LoginResponse> gmailSignUp({
    required _i11.GmailLoginRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gmailSignUp, [], {#request: request}),
            returnValue: _i9.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailSignUp, [], {#request: request}),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailSignUp, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i3.LoginResponse>);

  @override
  _i9.Future<_i4.SimpleApiResponse> resendEmailVerification({
    required _i12.UserEmailRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailVerification, [], {
              #request: request,
            }),
            returnValue: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resendEmailVerification, [], {
                  #request: request,
                }),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resendEmailVerification, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.SimpleApiResponse>);

  @override
  _i9.Future<_i3.LoginResponse> login({required _i13.LoginRequest? request}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#request: request}),
            returnValue: _i9.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [], {#request: request}),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i3.LoginResponse>);

  @override
  _i9.Future<_i3.LoginResponse> gmailLogin({
    required _i11.GmailLoginRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gmailLogin, [], {#request: request}),
            returnValue: _i9.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailLogin, [], {#request: request}),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailLogin, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i3.LoginResponse>);

  @override
  _i9.Future<_i4.SimpleApiResponse> forgetPassword({
    required _i12.UserEmailRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#request: request}),
            returnValue: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#forgetPassword, [], {#request: request}),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#forgetPassword, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i4.SimpleApiResponse>);

  @override
  _i9.Future<_i4.SimpleApiResponse> verifyCode({
    required _i14.VerifyCodeRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [], {#request: request}),
            returnValue: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#verifyCode, [], {#request: request}),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#verifyCode, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i4.SimpleApiResponse>);

  @override
  _i9.Future<_i4.SimpleApiResponse> resetPassword({
    required _i15.ResetPasswordRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#request: request}),
            returnValue: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resetPassword, [], {#request: request}),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resetPassword, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i4.SimpleApiResponse>);
}

/// A class which mocks [SocialAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialAuthService extends _i1.Mock implements _i16.SocialAuthService {
  @override
  _i9.Future<String> getGoogleIdToken() =>
      (super.noSuchMethod(
            Invocation.method(#getGoogleIdToken, []),
            returnValue: _i9.Future<String>.value(
              _i17.dummyValue<String>(
                this,
                Invocation.method(#getGoogleIdToken, []),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i17.dummyValue<String>(
                this,
                Invocation.method(#getGoogleIdToken, []),
              ),
            ),
          )
          as _i9.Future<String>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i18.AuthLocalDataSource {
  @override
  _i9.Future<void> saveLoginSession({_i5.LoginSessionDto? body}) =>
      (super.noSuchMethod(
            Invocation.method(#saveLoginSession, [], {#body: body}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearLoginSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearLoginSession, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i5.LoginSessionDto> getLoginSession() =>
      (super.noSuchMethod(
            Invocation.method(#getLoginSession, []),
            returnValue: _i9.Future<_i5.LoginSessionDto>.value(
              _FakeLoginSessionDto_3(
                this,
                Invocation.method(#getLoginSession, []),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i5.LoginSessionDto>.value(
              _FakeLoginSessionDto_3(
                this,
                Invocation.method(#getLoginSession, []),
              ),
            ),
          )
          as _i9.Future<_i5.LoginSessionDto>);
}

/// A class which mocks [DeviceIdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceIdService extends _i1.Mock implements _i19.DeviceIdService {
  @override
  _i9.Future<String> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i9.Future<String>.value(
              _i17.dummyValue<String>(
                this,
                Invocation.method(#getDeviceId, []),
              ),
            ),
            returnValueForMissingStub: _i9.Future<String>.value(
              _i17.dummyValue<String>(
                this,
                Invocation.method(#getDeviceId, []),
              ),
            ),
          )
          as _i9.Future<String>);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i20.FirebaseMessaging {
  @override
  _i6.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_4(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_4(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i6.FirebaseApp);

  @override
  bool get isAutoInitEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoInitEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i9.Stream<String>.empty(),
            returnValueForMissingStub: _i9.Stream<String>.empty(),
          )
          as _i9.Stream<String>);

  @override
  set app(_i6.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<_i7.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i9.Future<_i7.RemoteMessage?>.value(),
            returnValueForMissingStub: _i9.Future<_i7.RemoteMessage?>.value(),
          )
          as _i9.Future<_i7.RemoteMessage?>);

  @override
  _i9.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getAPNSToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAPNSToken, []),
            returnValue: _i9.Future<String?>.value(),
            returnValueForMissingStub: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<String?> getToken({
    String? vapidKey,
    String? serviceWorkerScriptPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [], {
              #vapidKey: vapidKey,
              #serviceWorkerScriptPath: serviceWorkerScriptPath,
            }),
            returnValue: _i9.Future<String?>.value(),
            returnValueForMissingStub: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i9.Future<bool>.value(false),
            returnValueForMissingStub: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i7.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, []),
            returnValue: _i9.Future<_i7.NotificationSettings>.value(
              _FakeNotificationSettings_5(
                this,
                Invocation.method(#getNotificationSettings, []),
              ),
            ),
            returnValueForMissingStub:
                _i9.Future<_i7.NotificationSettings>.value(
                  _FakeNotificationSettings_5(
                    this,
                    Invocation.method(#getNotificationSettings, []),
                  ),
                ),
          )
          as _i9.Future<_i7.NotificationSettings>);

  @override
  _i9.Future<_i7.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
    bool? providesAppNotificationSettings = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
              #providesAppNotificationSettings: providesAppNotificationSettings,
            }),
            returnValue: _i9.Future<_i7.NotificationSettings>.value(
              _FakeNotificationSettings_5(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                  #providesAppNotificationSettings:
                      providesAppNotificationSettings,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i9.Future<_i7.NotificationSettings>.value(
                  _FakeNotificationSettings_5(
                    this,
                    Invocation.method(#requestPermission, [], {
                      #alert: alert,
                      #announcement: announcement,
                      #badge: badge,
                      #carPlay: carPlay,
                      #criticalAlert: criticalAlert,
                      #provisional: provisional,
                      #sound: sound,
                      #providesAppNotificationSettings:
                          providesAppNotificationSettings,
                    }),
                  ),
                ),
          )
          as _i9.Future<_i7.NotificationSettings>);

  @override
  _i9.Future<void> setAutoInitEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoInitEnabled, [enabled]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDeliveryMetricsExportToBigQuery, [enabled]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setForegroundNotificationPresentationOptions,
              [],
              {#alert: alert, #badge: badge, #sound: sound},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
