// Mocks generated by Mockito 5.4.6 from annotations
// in tamyez_app/test/modules/auth/ui/screens/login/view_model/login_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tamyez_app/core/execution/operation_result.dart' as _i4;
import 'package:tamyez_app/modules/auth/domain/entities/login_params.dart'
    as _i6;
import 'package:tamyez_app/modules/auth/domain/entities/login_response_entity.dart'
    as _i5;
import 'package:tamyez_app/modules/auth/domain/use_case/gmail_login_use_case.dart'
    as _i8;
import 'package:tamyez_app/modules/auth/domain/use_case/login_use_case.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i2.LoginUseCase {
  @override
  _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>> call({
    required _i6.LoginParams? params,
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #params: params,
              #rememberMe: rememberMe,
            }),
            returnValue:
                _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i5.LoginResponseEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #params: params,
                      #rememberMe: rememberMe,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i5.LoginResponseEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #params: params,
                      #rememberMe: rememberMe,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>>);
}

/// A class which mocks [GmailLoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGmailLoginUseCase extends _i1.Mock implements _i8.GmailLoginUseCase {
  @override
  _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>> call({
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#rememberMe: rememberMe}),
            returnValue:
                _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i5.LoginResponseEntity>>(
                    this,
                    Invocation.method(#call, [], {#rememberMe: rememberMe}),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i5.LoginResponseEntity>>(
                    this,
                    Invocation.method(#call, [], {#rememberMe: rememberMe}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<_i5.LoginResponseEntity>>);
}
