// Mocks generated by Mockito 5.4.6 from annotations
// in tamyez_app/test/modules/auth/data/data_sources/remote/auth_remote_data_source_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tamyez_app/core/network/models/simple_api_response.dart' as _i4;
import 'package:tamyez_app/modules/auth/data/data_sources/remote/auth_api_client.dart'
    as _i5;
import 'package:tamyez_app/modules/auth/data/models/gmail_login_request.dart'
    as _i8;
import 'package:tamyez_app/modules/auth/data/models/login_request.dart' as _i10;
import 'package:tamyez_app/modules/auth/data/models/login_response.dart' as _i3;
import 'package:tamyez_app/modules/auth/data/models/reset_password_request.dart'
    as _i12;
import 'package:tamyez_app/modules/auth/data/models/sign_up_request.dart'
    as _i7;
import 'package:tamyez_app/modules/auth/data/models/sign_up_response.dart'
    as _i2;
import 'package:tamyez_app/modules/auth/data/models/user_email_request.dart'
    as _i9;
import 'package:tamyez_app/modules/auth/data/models/verify_code_request.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignUpResponse_0 extends _i1.SmartFake
    implements _i2.SignUpResponse {
  _FakeSignUpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleApiResponse_2 extends _i1.SmartFake
    implements _i4.SimpleApiResponse {
  _FakeSimpleApiResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiClient extends _i1.Mock implements _i5.AuthApiClient {
  @override
  _i6.Future<_i2.SignUpResponse> signUp(_i7.SignUpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i6.Future<_i2.SignUpResponse>.value(
              _FakeSignUpResponse_0(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.SignUpResponse>.value(
              _FakeSignUpResponse_0(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.SignUpResponse>);

  @override
  _i6.Future<_i3.LoginResponse> gmailSignUp(_i8.GmailLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#gmailSignUp, [request]),
            returnValue: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailSignUp, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailSignUp, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.LoginResponse>);

  @override
  _i6.Future<_i4.SimpleApiResponse> resendEmailVerification(
    _i9.UserEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailVerification, [request]),
            returnValue: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resendEmailVerification, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resendEmailVerification, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.SimpleApiResponse>);

  @override
  _i6.Future<_i3.LoginResponse> login(_i10.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i6.Future<_i3.LoginResponse>);

  @override
  _i6.Future<_i3.LoginResponse> gmailLogin(_i8.GmailLoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#gmailLogin, [request]),
            returnValue: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailLogin, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#gmailLogin, [request]),
              ),
            ),
          )
          as _i6.Future<_i3.LoginResponse>);

  @override
  _i6.Future<_i4.SimpleApiResponse> forgetPassword(
    _i9.UserEmailRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.SimpleApiResponse>);

  @override
  _i6.Future<_i4.SimpleApiResponse> verifyCode(
    _i11.VerifyCodeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [request]),
            returnValue: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#verifyCode, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#verifyCode, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.SimpleApiResponse>);

  @override
  _i6.Future<_i4.SimpleApiResponse> resetPassword(
    _i12.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.SimpleApiResponse>.value(
              _FakeSimpleApiResponse_2(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.SimpleApiResponse>);
}
