# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

    desc "Deploy a new version to Firebase App Distribution"
    lane :deploy_to_firebase_distribution do
        gradle(task: "clean assembleRelease")
        release = firebase_app_distribution(
            app: "1:364066125522:android:b58ddcf01e400daabc1f0b",
            groups:"tamyez-team",
            release_notes: "Finished Authentication module",
            android_artifact_type:"APK",
            android_artifact_path:"../build/app/outputs/apk/release/app-release.apk",
            service_credentials_file:"/home/mk369/.tamyez-app-405ad-firebase-adminsdk-fbsvc-e70ed7dfb1.json"
        )
    end
end
