// Mocks generated by Mockito 5.4.6 from annotations
// in tamyez_app/test/modules/auth/core/helpers/shared_test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tamyez_app/core/bootstrap/app_initializer.dart' as _i14;
import 'package:tamyez_app/core/entities/login_session_entity.dart' as _i11;
import 'package:tamyez_app/core/execution/operation_result.dart' as _i4;
import 'package:tamyez_app/modules/auth/domain/entities/login_params.dart'
    as _i10;
import 'package:tamyez_app/modules/auth/domain/entities/login_response_entity.dart'
    as _i8;
import 'package:tamyez_app/modules/auth/domain/entities/reset_password_params.dart'
    as _i13;
import 'package:tamyez_app/modules/auth/domain/entities/sign_up_params.dart'
    as _i6;
import 'package:tamyez_app/modules/auth/domain/entities/sign_up_response_entity.dart'
    as _i5;
import 'package:tamyez_app/modules/auth/domain/entities/user_email_params.dart'
    as _i9;
import 'package:tamyez_app/modules/auth/domain/entities/verify_code_params.dart'
    as _i12;
import 'package:tamyez_app/modules/auth/domain/repositories/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  _i3.Future<_i4.OperationResult<_i5.SignUpResponseEntity>> signUp({
    required _i6.SignUpParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {#params: params}),
            returnValue:
                _i3.Future<_i4.OperationResult<_i5.SignUpResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i5.SignUpResponseEntity>>(
                    this,
                    Invocation.method(#signUp, [], {#params: params}),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<_i5.SignUpResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i5.SignUpResponseEntity>>(
                    this,
                    Invocation.method(#signUp, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<_i5.SignUpResponseEntity>>);

  @override
  _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>> gmailSignUp() =>
      (super.noSuchMethod(
            Invocation.method(#gmailSignUp, []),
            returnValue:
                _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i8.LoginResponseEntity>>(
                    this,
                    Invocation.method(#gmailSignUp, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i8.LoginResponseEntity>>(
                    this,
                    Invocation.method(#gmailSignUp, []),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>);

  @override
  _i3.Future<_i4.OperationResult<bool>> resendEmailVerification({
    required _i9.UserEmailParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resendEmailVerification, [], {#params: params}),
            returnValue: _i3.Future<_i4.OperationResult<bool>>.value(
              _i7.dummyValue<_i4.OperationResult<bool>>(
                this,
                Invocation.method(#resendEmailVerification, [], {
                  #params: params,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<bool>>.value(
                  _i7.dummyValue<_i4.OperationResult<bool>>(
                    this,
                    Invocation.method(#resendEmailVerification, [], {
                      #params: params,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<bool>>);

  @override
  _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>> login({
    required _i10.LoginParams? params,
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #params: params,
              #rememberMe: rememberMe,
            }),
            returnValue:
                _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i8.LoginResponseEntity>>(
                    this,
                    Invocation.method(#login, [], {
                      #params: params,
                      #rememberMe: rememberMe,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i8.LoginResponseEntity>>(
                    this,
                    Invocation.method(#login, [], {
                      #params: params,
                      #rememberMe: rememberMe,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>);

  @override
  _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>> gmailLogin({
    required bool? rememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gmailLogin, [], {#rememberMe: rememberMe}),
            returnValue:
                _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i8.LoginResponseEntity>>(
                    this,
                    Invocation.method(#gmailLogin, [], {
                      #rememberMe: rememberMe,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>.value(
                  _i7.dummyValue<_i4.OperationResult<_i8.LoginResponseEntity>>(
                    this,
                    Invocation.method(#gmailLogin, [], {
                      #rememberMe: rememberMe,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<_i8.LoginResponseEntity>>);

  @override
  _i3.Future<_i11.LoginSessionEntity?> getLoginSession() =>
      (super.noSuchMethod(
            Invocation.method(#getLoginSession, []),
            returnValue: _i3.Future<_i11.LoginSessionEntity?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i11.LoginSessionEntity?>.value(),
          )
          as _i3.Future<_i11.LoginSessionEntity?>);

  @override
  _i3.Future<_i4.OperationResult<bool>> forgetPassword({
    required _i9.UserEmailParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#params: params}),
            returnValue: _i3.Future<_i4.OperationResult<bool>>.value(
              _i7.dummyValue<_i4.OperationResult<bool>>(
                this,
                Invocation.method(#forgetPassword, [], {#params: params}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<bool>>.value(
                  _i7.dummyValue<_i4.OperationResult<bool>>(
                    this,
                    Invocation.method(#forgetPassword, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<bool>>);

  @override
  _i3.Future<_i4.OperationResult<bool>> verifyCode({
    required _i12.VerifyCodeParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [], {#params: params}),
            returnValue: _i3.Future<_i4.OperationResult<bool>>.value(
              _i7.dummyValue<_i4.OperationResult<bool>>(
                this,
                Invocation.method(#verifyCode, [], {#params: params}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<bool>>.value(
                  _i7.dummyValue<_i4.OperationResult<bool>>(
                    this,
                    Invocation.method(#verifyCode, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<bool>>);

  @override
  _i3.Future<_i4.OperationResult<bool>> resetPassword({
    required _i13.ResetPasswordParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#params: params}),
            returnValue: _i3.Future<_i4.OperationResult<bool>>.value(
              _i7.dummyValue<_i4.OperationResult<bool>>(
                this,
                Invocation.method(#resetPassword, [], {#params: params}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.OperationResult<bool>>.value(
                  _i7.dummyValue<_i4.OperationResult<bool>>(
                    this,
                    Invocation.method(#resetPassword, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.OperationResult<bool>>);
}

/// A class which mocks [AppInitializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppInitializer extends _i1.Mock implements _i14.AppInitializer {
  @override
  _i3.Future<void> initializeLight() =>
      (super.noSuchMethod(
            Invocation.method(#initializeLight, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> initializeHeavy() =>
      (super.noSuchMethod(
            Invocation.method(#initializeHeavy, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void initAuthAndUserProvider({
    required _i11.LoginSessionEntity? session,
    bool? remembered = true,
  }) => super.noSuchMethod(
    Invocation.method(#initAuthAndUserProvider, [], {
      #session: session,
      #remembered: remembered,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthAndUserProvider() => super.noSuchMethod(
    Invocation.method(#clearAuthAndUserProvider, []),
    returnValueForMissingStub: null,
  );
}
