// Mocks generated by Mockito 5.4.6 from annotations
// in tamyez_app/test/modules/core/shared/widget_testing_shared_setups.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tamyez_app/core/layers/localization/enums/languages_enum.dart'
    as _i3;
import 'package:tamyez_app/core/layers/localization/l10n/manager/localization_manager.dart'
    as _i2;
import 'package:tamyez_app/core/layers/theme/manager/theme_manager.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalizationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationManager extends _i1.Mock
    implements _i2.LocalizationManager {
  @override
  _i3.LanguagesEnum get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _i3.LanguagesEnum.en,
            returnValueForMissingStub: _i3.LanguagesEnum.en,
          )
          as _i3.LanguagesEnum);

  @override
  bool get isEnglish =>
      (super.noSuchMethod(
            Invocation.getter(#isEnglish),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setInitLocal(_i3.LanguagesEnum? initLocal) => super.noSuchMethod(
    Invocation.method(#setInitLocal, [initLocal]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> changeLocal(_i3.LanguagesEnum? languageEnum) =>
      (super.noSuchMethod(
            Invocation.method(#changeLocal, [languageEnum]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getSavedLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocal, []),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeManager extends _i1.Mock implements _i6.ThemeManager {
  @override
  _i5.Brightness get currentTheme =>
      (super.noSuchMethod(
            Invocation.getter(#currentTheme),
            returnValue: _i5.Brightness.dark,
            returnValueForMissingStub: _i5.Brightness.dark,
          )
          as _i5.Brightness);

  @override
  bool get isDarkTheme =>
      (super.noSuchMethod(
            Invocation.getter(#isDarkTheme),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setInitTheme(_i5.Brightness? initTheme) => super.noSuchMethod(
    Invocation.method(#setInitTheme, [initTheme]),
    returnValueForMissingStub: null,
  );

  @override
  void changeTheme(_i5.Brightness? newTheme) => super.noSuchMethod(
    Invocation.method(#changeTheme, [newTheme]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i7.NavigatorObserver {
  @override
  void didPush(_i7.Route<dynamic>? route, _i7.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i7.Route<dynamic>? route, _i7.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(_i7.Route<dynamic>? route,
      _i7.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i7.Route<dynamic>? newRoute,
    _i7.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(_i7.Route<dynamic>? topRoute,
      _i7.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(_i7.Route<dynamic>? route,
      _i7.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
